decide/lic0.cpp, decide/lic0.test.cpp
Fixes #16.
Add proper functionality for the LIC 0 function, as well as tests.
=> feat: Add LIC 0

Makefile
=> Update make test to run all test files

decide/utils.hpp
=> feat: Add file for util functions

decide/lic12.cpp, decide/lic12.test.cpp, decide/lics.hpp
=> feat: Add LIC12

decide/lic11.cpp, decide/lic11.test.cpp, decide/lics.hpp
=> feat: Add LIC11

decide/lic7.cpp, decide/lic7.test.cpp, decide/lics.hpp
=> feat: Add LIC7

decide/lic5.cpp, decide/lic5.test.cpp, decide/lics.hpp
resolves #6
LIC 5 is true when "There exists at least one set of two consecutive data points, (X[i],Y[i]) and (X[j],Y[j]), such that X[j] - X[i] <0. (where i = j-1)"
=> feat: add LIC 5

decide/decide.hpp
=> Make `Coordinate` equality operator const

decide/lic12.cpp
=> fix: Fix LIC12 OBOE

decide/lic0.cpp, decide/lic0.test.cpp
=> fix: Fix LIC0

decide/lic1.cpp, decide/lic1.test.cpp, decide/lics.hpp
This fixes #2 by adding both code and testing for LIC1.
=> feat: Add LIC1

decide/utils.hpp
This adds a function in utils.hpp that checks whether three points can be contained within a circle of a given radius. Will be used in the implementation of at least three LIC functions (#2 , #9 and #85).
=> feat: Add function to utils for checking if points can be contained by circle

decide/lic1.cpp, decide/lic1.test.cpp
This corrects the incorrect implementation of LIC1 and fixes #89.
=> fix: Correct the implementation of LIC1

decide/decide.cpp, decide/decide.hpp, decide/decide.test.cpp
=> feat: Implement PUM functionality

decide/utils.hpp, decide/utils.test.cpp
=> feat: Add function that calculates triangle area

decide/lic10.cpp, decide/lic10.test.cpp, decide/lics.hpp
=> feat: Add LIC10

decide/utils.hpp, decide/utils.test.cpp
=> feat: Add angle between points function

decide/decide.cpp, decide/decide.hpp, decide/decide.test.cpp
Fixes #90.
Note, depends on #88
=> feat: Add FUV

decide/lic6.cpp, decide/lic6.test.cpp, decide/lics.hpp
=> feat: Add LIC6

decide/lic14.cpp, decide/lic14.tests.cpp
=> feat: add LIC 14

decide/lic8.cpp, decide/lic8.test.cpp, decide/lics.hpp
=> feat: Add LIC8

decide/lic4.cpp, decide/lic4.test.cpp, decide/lics.hpp
=> Feat: Add LIC 4

decide/lic9.cpp, decide/lic9.test.cpp, decide/lics.hpp
=> feat: Add LIC #9

decide/lic13.cpp, decide/lic13.test.cpp, decide/lics.hpp
resolves #14
Currently does not compile, waiting for circle util PR #67 
Also needs to add tests, and add to lics.hpp
=> feat: add lic 13

decide/lic2.cpp, decide/lic2.test.cpp
=> feat: Add LIC 2

decide/lics.hpp
=> fix: Add missing LIC declarations

Makefile, decide/lic2.cpp, decide/lic9.cpp, decide/utils.cpp, decide/utils.hpp
=> fix: Solves util declaration problems

.gitignore, Makefile, decide/decide.cpp, decide/decide.hpp, decide/decide.test.cpp, decide/main.cpp, tests/launch/decisions.cpp
Fixes #93 
Note: depends on #88 and #92
=> feat: Add launch

docs/CONTRIBUTING.md
This fixes #111 by adding a requirement that the code compiles and all tests run, and also fixes #115 by updating the section on PR merge blocks to reflect the current process.
=> doc:  Update contribution rules

docs/README.md
This fixes #124 by updating the section on individual contributions, to showcase what each member has primarily been working on.
fix
one test
_(It doesn't)_
_(No code, no format)_
=> doc: Update contribution statement

Makefile
Change the binary file's name in the Makefile to fix #129.
fix
one test
=> fix: Correct binary name in makefile
